# Generated by Django 5.2.17 on 2026-09-25 13:32

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='galeria/')),
                ('descricao', tinymce.models.HTMLField()),
                ('data', models.DateField(auto_now=True)),
            ],
        ),
    ]
